[versions]
metro = "0.11.4"
kache = "2.1.1"
app-platform = "0.0.10-SNAPSHOT"
kotlin = "2.3.20-RC2"
sphereon-idk = "0.25.0-SNAPSHOT"
kotlinx-coroutines = "1.10.1"
kotlin-logging = "7.0.3"
mockk = "1.13.14"

[libraries]
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

amz-metro-public = { module = "software.amazon.app.platform:metro-public", version.ref = "app-platform" }
amz-metro-impl = { module = "software.amazon.app.platform:metro-impl", version.ref = "app-platform" }
amz-kotlin-scope-public = { module = "software.amazon.app.platform:scope-public", version.ref = "app-platform" }
amz-di-common-public = { module = "software.amazon.app.platform:di-common-public", version.ref = "app-platform" }

sphereon-core-api-public = { module = "com.sphereon.idk:lib-core-api-public", version.ref = "sphereon-idk" }
sphereon-core-api-default = { module = "com.sphereon.idk:lib-core-api-default", version.ref = "sphereon-idk" }
sphereon-core-logger-console = { module = "com.sphereon.idk:lib-core-loggers-console-logger", version.ref = "sphereon-idk" }
sphereon-ktor-httpclient = { module = "com.sphereon.idk:lib-http-ktor-http-client", version.ref = "sphereon-idk" }
sphereon-compat = { module = "com.sphereon.idk:lib-core-compat", version.ref = "sphereon-idk" }

# Auth Bridge
sphereon-auth-bridge-public = { module = "com.sphereon.idk:lib-openid-oid4vp-auth-bridge-public", version.ref = "sphereon-idk" }
sphereon-auth-bridge-impl = { module = "com.sphereon.idk:lib-openid-oid4vp-auth-bridge-impl", version.ref = "sphereon-idk" }

# OAuth2 Server Authorization
sphereon-oauth2-server-authorization-public = { module = "com.sphereon.idk:lib-oauth2-server-authorization-public", version.ref = "sphereon-idk" }
sphereon-oauth2-server-authorization-impl = { module = "com.sphereon.idk:lib-oauth2-server-authorization-impl", version.ref = "sphereon-idk" }

kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlin-logging-jvm = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin-logging" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

[bundles]
app-platform-di = [
    "amz-metro-public",
    "amz-metro-impl",
    "amz-di-common-public",
    "amz-kotlin-scope-public"
]

[plugins]
metro = { id = "dev.zacsweers.metro", version.ref = "metro" }
